spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:sqlserver://employee-microservice.database.windows.net:1433;databaseName=employee_db;encrypt=true;trustServerCertificate=true
    username: sqladmin
    password: Arpitha@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

instance:
    prefer-ip-address: true